spring:
  application:
    name: Neoike
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/neoike
    username: neoike
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: debug

sneaker:
  images:
    dir: 'src/main/resources/sneaker/images/'

image:
  file:
    maxSize: 3MB
    mbUnit: 1000000
    overHead: 1.3
    supportFormatTypes:
      - PNG
      - JPG
      - JPEG
jwt:
  header: Authorization
  secret: cHJncm1zLWJlLWRldmNvdXJzZS1CRS0wMi1OZW9pa2Utc3ByaW5nLWJvb3QtYmFja2VuZC1wcm9qZWN0LWp3dC10b2tlbi1wcmdybXMtYmUtZGV2Y291cnNlLUJFLTAyLU5lb2lrZS1zcHJpbmctYm9vdC1iYWNrZW5kLXByb2plY3Qtand0LXRva2Vu
  token-validity-in-seconds: 86400
